version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc@123
      - POSTGRES_DB=CatalogDb
    expose:
      - "5433"
    restart: always
    ports:
       - "5433:5433"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/ 
    command: -p 5433

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc@123
      - POSTGRES_DB=BasketDb
    expose:
      - "5434"
    restart: always
    ports:
       - "5434:5434"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/ 
    command: -p 5434

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
       - "6379:6379"
 
  catelog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5433;Database=CatalogDb;User Id=postgres;Password=abc@123;Include Error Detail=true 
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5434;Database=BasketDb;User Id=postgres;Password=abc@123;Include Error Detail=true 
      - ConnectionStrings__Redis=distributedcache:6379
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
