version: '3.4'

services:
  catalogdb:
    image: postgres

  catelog.api:
    image: ${DOCKER_REGISTRY-}catelogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catelog.API/Dockerfile

volumes:
  postgres_catalog:    
  

